### ISSUE TITLE
Configurable Time when Ex-Raids appear on Map

### ISSUE THREAD

**Issue by quentar82** [florianbecker/PokemonBotMap#11]
At the moment Ex-Raids posted were shown on Map 96hrs before Ex-Raids start. The Timerange when Ex-Raids appears on Map should be configurable (hrs) within setting for showing Ex-Raids immediately when posted.

**Comment by MeisterMauzi** [comment]
This issue is addressed in pull request https://github.com/florianbecker/PokemonBotMap/pull/17
