### ISSUE TITLE
Templates for body

### ISSUE THREAD

**Issue by florianbecker** [florianbecker/PokemonBotMap#6]
Create a system to use templates

Templates:
More relevant data first template
Current standard look
Minimal template
...

**Comment by Chefkeks** [comment]
I think this is implemented too with the last update if the keys/buttons are meant with the template. Via config the RAID_POLL_UI_ORDER can be defined which allows to easily re-arrange the button/key rows.

**Comment by florianbecker** [comment]
Button order ist inserted. So body needs to be configureable.
